name: aRNAque
channels:
  - bioconda
dependencies:
  - python=3.7
  - viennarna=2.4.14
  - numpy
  - pandas
  - pip:
    - multiprocess
    - datetime
    - scipy
    - matplotlib
    - ast
    - seaborn
